name: format-check

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    name: Run build on Windows
    runs-on: [self-hosted, Windows]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: configure
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 -S ./ -B build
      
      - name: format-check 
        run: |
          cmake --build build --target format-check